"""Security and packaged-asset contracts for the graph HTML renderer."""

from __future__ import annotations

import json
import math
import re
from importlib import resources

import pytest

from sigwood.outputs.graph import _MARKER, _embed_payload, render_graph_html


def _player_template() -> str:
    return (
        resources.files("sigwood.outputs")
        .joinpath("graph_player.html")
        .read_text(encoding="utf-8")
    )


def _payload() -> dict[str, object]:
    return {
        "meta": {
            "generator": "sigwood",
            "display_utc": True,
            "default_window_note": "showing the default 7d window",
            "source": "192.0.2.40/conn.log",
        },
        "srcNodes": ["192.0.2.40"],
        "dstNodes": ["198.51.100.24"],
        "svcNodes": ["443/tcp"],
        "flows": [],
    }


def _data_script_blob(html: str) -> str:
    """Return the JSON text from the dedicated first data script."""
    prefix = "const DATA = "
    _, after_prefix = html.split(prefix, 1)
    blob, _ = after_prefix.split(";</script>", 1)
    return blob


@pytest.mark.parametrize(
    ("template", "count"),
    [
        ("<script>const DATA = null;</script>", 0),
        (f"{_MARKER} then {_MARKER}", 2),
    ],
)
def test_embed_payload_requires_one_marker(template: str, count: int) -> None:
    with pytest.raises(ValueError, match=rf"exactly one payload marker \(found {count}\)"):
        _embed_payload(_payload(), template)


def test_marker_valued_log_data_is_preserved_after_single_replacement() -> None:
    payload = {"host": "192.0.2.44", "note": _MARKER}

    rendered = _embed_payload(payload, f"before:{_MARKER}:after")

    assert rendered == f'before:{{"host":"192.0.2.44","note":"{_MARKER}"}}:after'


def test_hostile_script_tokens_cannot_close_the_data_script() -> None:
    hostile = "< / </script><script>alert('192.0.2.55')</script>"
    payload = {"host": "192.0.2.55", "label": hostile}
    rendered = _embed_payload(payload, f"<script>const DATA = {_MARKER};</script>")
    blob = _data_script_blob(rendered)

    assert "<" not in blob
    assert r"\u003c / \u003c/script>\u003cscript>" in blob
    assert rendered.count("</script>") == 1
    assert json.loads(blob) == payload


@pytest.mark.parametrize("nonfinite", [math.nan, math.inf, -math.inf])
def test_embed_payload_rejects_nonfinite_values(nonfinite: float) -> None:
    with pytest.raises(ValueError):
        _embed_payload({"metric": nonfinite}, _MARKER)


def test_renderer_loads_the_packaged_player_resource() -> None:
    template = _player_template()
    artifact = render_graph_html(_payload())

    assert template.count(_MARKER) == 1
    assert _MARKER not in artifact
    assert json.loads(_data_script_blob(artifact)) == _payload()


def test_player_footer_display_and_window_metadata_contracts() -> None:
    template = _player_template()

    assert 'const footer = `generated by ${M.generator || "sigwood"} · hunt logs like this: sigwood hunt PATH`;' in template
    assert '$("winnote").textContent = [footer, M.default_window_note].filter(Boolean).join(" · ");' in template
    assert 'const clockPart = (d, local, utc) => M.display_utc ? d[utc]() : d[local]();' in template
    assert 'if (M.display_utc) d.setUTCHours(0, 0, 0, 0);' in template
    assert 'if (M.display_utc) return "UTC";' in template

    # A downloaded replay is part of the rendered operator surface. Its date
    # must obey the same display-timezone switch as its clock fields.
    clip_start = template.index("const name = `sigwood-graph_clip_")
    clip_end = template.index(";", clip_start)
    clip_name = template[clip_start:clip_end]
    assert 'clockPart(d, "getFullYear", "getUTCFullYear")' in clip_name
    assert 'clockPart(d, "getMonth", "getUTCMonth")' in clip_name
    assert 'clockPart(d, "getDate", "getUTCDate")' in clip_name


def test_clip_export_reuses_the_data_script_escape_before_reembedding() -> None:
    """The downloaded replay cannot reintroduce a closing script token."""
    template = _player_template()
    payload = {"label": "</script><script>alert('x')</script>"}

    # Pin the executable clip boundary, not merely the server-side renderer.
    assert r'const blob = JSON.stringify(payload).replace(/</g, "\\u003c");' in template
    blob = json.dumps(payload, separators=(",", ":"), ensure_ascii=True).replace(
        "<", "\\u003c",
    )
    rebuilt = f"<script>const DATA = {blob};</script>"

    assert "<" not in blob
    assert rebuilt.count("</script>") == 1
    assert json.loads(blob) == payload


def test_player_is_self_contained_and_has_no_stale_poc_or_dash_residue() -> None:
    template = _player_template()
    for forbidden in (
        r"https?://",
        r"(?<!:)//[a-z0-9][a-z0-9.-]*(?:[/:?#]|$)",
        r"<\s*link\b",
        r"<\s*script\s+[^>]*\bsrc\s*=",
        r"<\s*(?:iframe|object|embed|source|img|video|audio|track)\b",
        r"<[^>]*\b(?:src|href|poster|data)\s*=",
        r"@import\b",
        r"(?<![a-z0-9_])url\s*\(",
        r"data\s*:",
        r"fetch\s*\(",
        r"xmlhttprequest\b",
        r"websocket\b",
        r"navigator\s*\.\s*sendbeacon\b",
        r"import\s*\(",
        r"innerhtml\b",
        r"insertadjacenthtml\b",
        r"document\s*\.\s*write\s*\(",
        r"eval\s*\(",
        r"new\s+function\b",
        r"new\s+worker\s*\(",
        r"new\s+eventsource\s*\(",
        r"importscripts\s*\(",
        r"serviceworker\b",
    ):
        assert re.search(forbidden, template, flags=re.IGNORECASE) is None, forbidden

    # The player intentionally creates a local Blob download through DOM
    # properties. Attribute checks above are tag-scoped so this path remains
    # allowed without permitting external resource markup.
    assert "URL.createObjectURL(new Blob(" in template
    assert "link.href = url; link.download = name" in template

    lowered = template.lower()
    for stale in ("poc", "newton", "\u2013", "\u2014"):
        assert stale not in lowered


@pytest.mark.parametrize(
    ("pattern", "variant"),
    [
        (r"fetch\s*\(", "fetch (target)"),
        (r"new\s+function\b", "new\nFunction(code)"),
        (r"<\s*script\s+[^>]*\bsrc\s*=", "<script\n src = target>"),
        (r"<[^>]*\b(?:src|href|poster|data)\s*=", "<img\n src = target>"),
        (r"(?<![a-z0-9_])url\s*\(", "url (target)"),
        (r"new\s+worker\s*\(", "new\nWorker (target)"),
    ],
)
def test_player_resource_patterns_cover_whitespace_variants(
    pattern: str, variant: str,
) -> None:
    """The self-containment patterns catch spacing changes in sink syntax."""
    assert re.search(pattern, variant, flags=re.IGNORECASE) is not None
