"""Era planning, aggregate report facts, and renderer-ready cards."""

from sigwood.era.eligibility import (
    DisplayDayEligibility,
    SourcePartition,
    eligible_display_day,
    eligible_iso_weeks,
)
from sigwood.era.observation import (
    Availability,
    CaptureLossInterval,
    Completeness,
    FamilyDayObservation,
    ParseUsability,
    PeerLossSummary,
    summarize_capture_loss,
)
from sigwood.era.measurement import (
    D34_RSS_LIMIT_BYTES,
    D34Outcome,
    D34Receipt,
    normalized_maxrss_bytes,
    not_measured_d34,
)
from sigwood.era.domains import DOMAIN_CAP, DomainLedger, DomainLedgerFacts, registrable_domain
from sigwood.era.planner import (
    ArchivePlan,
    ArchivePlanner,
    BaselineReconciliation,
    WorkEstimate,
)
from sigwood.era.report import (
    EXTERNAL_ADDRESS_CAP,
    EraCard,
    EraReducer,
    EraShard,
    EraSlot,
    ExternalAddressFact,
    InspectHandoff,
    ReportInterval,
    activity_card,
    busiest_minute_card,
    calendar_card,
    domain_arrival_card,
    canonical_identity_payload,
    compose_inspect_handoff,
    compose_planned_inspect_handoff,
    largest_outbound_card,
    longest_connection_card,
    render_text_report,
    transport_share_card,
    utc_shard_label,
)

__all__ = [
    "ArchivePlan",
    "ArchivePlanner",
    "Availability",
    "BaselineReconciliation",
    "CaptureLossInterval",
    "Completeness",
    "D34Outcome",
    "D34Receipt",
    "D34_RSS_LIMIT_BYTES",
    "DOMAIN_CAP",
    "DomainLedger",
    "DomainLedgerFacts",
    "DisplayDayEligibility",
    "EXTERNAL_ADDRESS_CAP",
    "EraCard",
    "EraReducer",
    "EraShard",
    "EraSlot",
    "ExternalAddressFact",
    "InspectHandoff",
    "FamilyDayObservation",
    "PeerLossSummary",
    "ParseUsability",
    "ReportInterval",
    "SourcePartition",
    "WorkEstimate",
    "eligible_display_day",
    "eligible_iso_weeks",
    "activity_card",
    "busiest_minute_card",
    "calendar_card",
    "domain_arrival_card",
    "canonical_identity_payload",
    "compose_inspect_handoff",
    "compose_planned_inspect_handoff",
    "largest_outbound_card",
    "longest_connection_card",
    "render_text_report",
    "registrable_domain",
    "transport_share_card",
    "normalized_maxrss_bytes",
    "not_measured_d34",
    "summarize_capture_loss",
    "utc_shard_label",
]
